// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate/introspection 用。Neon の pooler 経由だと migrate が失敗することがあるため、
    // DIRECT_URL（pooler を通さない direct 接続）が設定されていればそちらを優先する。
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
